### ISSUE TITLE
新着情報を載せる機能が欲しい

### ISSUE THREAD

**Issue by tadanet3** [K-Sakanoshita/takeaway#12]
日本人は新し物好きなので、新着情報や更新情報を表示する機能が欲しい。
過去一週間以内に登録された店名を一覧表示し、店名を押下すると、地図も移動する。
画面上には表示する場所が無いので、ズームボタンの上に新着ボタンを作って、それを押下すると、一覧表示する。

**Comment by K-Sakanoshita** [comment]
たださんが作って頂いたリスト内で新着表示する機能で賄えそうですが如何でしょうか？

**Comment by tadanet3** [comment]
はい、賄えると考えます。
